/**
 * FROGSTER MASH.  Fifteen tokens in, thirty out.
 *
 * A creature-builder with a fight on the end of it.  The player assembles a
 * Frogster out of six parts taken off a conveyor belt -- two legs, two arms,
 * a body and a head, in that order -- and then it fights one the machine built
 * the same way, out of the same parts, under the same rules.
 *
 * THE WHOLE GAME IS THE SIX CHOICES.  The fight is turn-based and short and
 * has exactly two buttons in it, because everything that decides it was
 * decided on the belt: which elements you took, what they are strong and weak
 * against, and whether you took enough of one to earn the synergy.  A player
 * who reads the cards wins; a player who grabs the biggest number does not,
 * because the biggest number is an element the enemy happens to resist.
 *
 * THE ARITHMETIC IS IN ONE PLACE.  `statsOf` turns a part into four numbers,
 * `assemble` turns six parts into a monster, and `damage` is the only thing
 * that takes health off anybody.  The enemy is generated by the same two
 * functions the player's belt uses, so there is no second set of rules for it
 * to be unfair with.
 *
 * NOTHING IN HERE TOUCHES THE LEDGER.  The shell charged the fifteen when the
 * player pressed PLAY on the how-to card and it pays the thirty on `api.win`,
 * once, guarded by its own latch -- this file only ever says which of the two
 * happened, and says it exactly once (`ended`).
 */

import Phaser from 'phaser';
import { PALETTE } from '../render/palette';
import { audio } from '../core/audio';
import { button, centerText, text } from '../core/ui';
import { GAME_W } from '../render/pixelScaler';
import type { MinigameApi, MinigameModule } from './types';

// ===================================================================== rules

export type Element = 'fire' | 'water' | 'grass' | 'electric' | 'steel' | 'ground';
export type Slot = 'legL' | 'legR' | 'armL' | 'armR' | 'body' | 'head';

/** The order the six parts are chosen in, and the order they are named in. */
const ORDER: Slot[] = ['legL', 'legR', 'armL', 'armR', 'body', 'head'];
const SLOT_NAME: Record<Slot, string> = {
  legL: 'LEFT LEG',
  legR: 'RIGHT LEG',
  armL: 'LEFT ARM',
  armR: 'RIGHT ARM',
  body: 'BODY ARMOR',
  head: 'HEAD',
};

/** Every element's four numbers, on the one-to-five scale the cards show. */
const BASE: Record<Element, { atk: number; def: number; spd: number; hp: number }> = {
  fire: { atk: 5, def: 2, spd: 4, hp: 3 },
  water: { atk: 3, def: 4, spd: 3, hp: 4 },
  grass: { atk: 3, def: 3, spd: 3, hp: 5 },
  electric: { atk: 4, def: 2, spd: 5, hp: 2 },
  steel: { atk: 2, def: 5, spd: 1, hp: 5 },
  ground: { atk: 4, def: 4, spd: 2, hp: 4 },
};
const ELEMENTS = Object.keys(BASE) as Element[];

/** What each element beats.  `WEAK[a]` is what beats `a`, and they agree. */
const STRONG: Record<Element, Element[]> = {
  fire: ['grass', 'steel'],
  water: ['fire', 'ground'],
  grass: ['water', 'ground'],
  electric: ['water'],
  steel: ['grass'],
  ground: ['fire', 'electric', 'steel'],
};
const WEAK: Record<Element, Element[]> = {
  fire: ['water', 'ground'],
  water: ['grass', 'electric'],
  grass: ['fire', 'steel'],
  electric: ['ground'],
  steel: ['fire', 'ground'],
  ground: ['water', 'grass'],
};

const STRONG_MUL = 1.5;
const WEAK_MUL = 0.75;
/** Power Rating 1..5, as a multiplier on the part's PRIMARY attributes. */
const POWER_MUL = [0, 0.8, 0.9, 1.0, 1.1, 1.2];
/** Four of six parts sharing an element is worth a tenth, both ways. */
const SYNERGY_AT = 4;
const SYNERGY_MUL = 1.1;

/** One attack's element against one defending element. */
export function effect(att: Element, def: Element): number {
  if (STRONG[att].includes(def)) return STRONG_MUL;
  if (WEAK[att].includes(def)) return WEAK_MUL;
  return 1;
}

const EL_COLOUR: Record<Element, number> = {
  fire: 0xff7a3d,
  water: 0x46a0e0,
  grass: 0x6fbb6a,
  electric: 0xffd45e,
  steel: 0x8e9cad,
  ground: 0xa8754a,
};
const EL_DARK: Record<Element, number> = {
  fire: 0xa8451f,
  water: 0x1f5c8a,
  grass: 0x3f7a4a,
  electric: 0xc77a1b,
  steel: 0x3a4a5c,
  ground: 0x6b4a2f,
};

export interface Part {
  slot: Slot;
  el: Element;
  /** 1..5.  Shown on every card and folded into the primary attributes. */
  power: number;
  atk: number;
  def: number;
  spd: number;
  hp: number;
}

/**
 * What a part of this element at this power contributes.
 *
 * Each slot has a job and the numbers follow it: legs are speed with a little
 * attack behind them, arms are attack, the body is defence and health and
 * pays for it in speed, and the head is the smaller half of the body.  The
 * Power Rating multiplies the PRIMARY attributes only -- a power-five leg is
 * faster, not tougher.
 *
 * The armour's speed penalty comes off its own element's DEFENCE, which is
 * what makes steel both the heaviest plate in the game and the slowest,
 * without either being written down as a special case.
 */
export function statsOf(slot: Slot, el: Element, power: number): Part {
  const b = BASE[el];
  const p = POWER_MUL[power];
  const mk = (atk: number, def: number, spd: number, hp: number): Part => ({
    slot, el, power, atk, def, spd, hp,
  });
  switch (slot) {
    case 'legL':
    case 'legR':
      return mk(b.atk * 0.25 * p, b.def * 0.1, b.spd * p, b.hp * 0.3);
    case 'armL':
    case 'armR':
      return mk(b.atk * p, b.def * 0.1, b.spd * 0.1, b.hp * 0.3);
    case 'body':
      return mk(0, b.def * 1.2 * p, -(b.def * 0.35), b.hp * 1.6 * p);
    default:
      return mk(0, b.def * 0.8 * p, 0, b.hp * 1.0 * p);
  }
}

/** Health and damage are scaled off the 1-5 numbers so a fight runs ~7 hits. */
const HP_SCALE = 8;
const ATK_SCALE = 8;
/** How much total defence is worth: damage is divided by 1 + def/this. */
const DEF_SOFT = 10;

export interface Monster {
  parts: Record<Slot, Part>;
  atk: number;
  def: number;
  spd: number;
  hp: number;
  maxHp: number;
  /** The element four or more of the six parts share, if there is one. */
  synergy: Element | null;
}

export function assemble(parts: Record<Slot, Part>): Monster {
  const all = ORDER.map((s) => parts[s]);
  const sum = (f: (p: Part) => number): number => all.reduce((a, p) => a + f(p), 0);
  const count = new Map<Element, number>();
  for (const p of all) count.set(p.el, (count.get(p.el) ?? 0) + 1);
  let synergy: Element | null = null;
  for (const [el, n] of count) if (n >= SYNERGY_AT) synergy = el;
  const hp = Math.max(1, Math.round(sum((p) => p.hp) * HP_SCALE));
  return {
    parts,
    atk: sum((p) => p.atk),
    def: sum((p) => p.def),
    // The armour's penalty is already negative, so this is one sum and not a
    // sum with a subtraction hiding in it.
    spd: sum((p) => p.spd),
    hp,
    maxHp: hp,
    synergy,
  };
}

export interface Hit {
  dmg: number;
  /** 'strong' | 'weak' | 'neutral', from the defender's armour and head. */
  band: 'strong' | 'weak' | 'neutral';
  el: Element;
  synergy: boolean;
}

/**
 * One swing, and the only thing in the game that takes health off anybody.
 *
 * The arm's attack and its Power Rating make the raw number; the defender's
 * total defence divides it; the elements decide the rest.  Defence against an
 * attack is the AVERAGE of what the body armour and the head think of it, so
 * a player who plates themselves in one element is resisted or shredded
 * wholesale and a player who mixes is neither.
 *
 * `vary` is the small roll that stops a fight being arithmetic the player can
 * do in their head.  It is injectable so a test can take it out.
 */
export function damage(att: Monster, defend: Monster, arm: 'armL' | 'armR', vary = Math.random): Hit {
  const a = att.parts[arm];
  const el = a.el;
  const raw = a.atk * POWER_MUL[a.power] * ATK_SCALE;
  const eff = (effect(el, defend.parts.body.el) + effect(el, defend.parts.head.el)) / 2;

  // SYNERGY, BOTH WAYS.  The attacker's own element hits a tenth harder, and a
  // defender whose four-part element resists what is coming takes a tenth less.
  const synAtt = att.synergy === el;
  let mul = synAtt ? SYNERGY_MUL : 1;
  if (defend.synergy && STRONG[defend.synergy].includes(el)) mul /= SYNERGY_MUL;

  const roll = 0.9 + vary() * 0.2;
  const dmg = Math.max(1, Math.round((raw * eff * mul * roll) / (1 + defend.def / DEF_SOFT)));
  return {
    dmg,
    band: eff > 1.02 ? 'strong' : eff < 0.98 ? 'weak' : 'neutral',
    el,
    synergy: synAtt,
  };
}

// ================================================================ generation

const rnd = (n: number): number => Math.floor(Math.random() * n);

/**
 * Five boxes for one stage, and no two of them the same.
 *
 * "Do not place identical options in all five boxes" is the floor; this goes
 * further and makes every box a different element/power pair, so there is
 * always something to compare.  Five of six elements appear, which is what
 * makes the choice a choice.
 */
function offerFor(slot: Slot): Part[] {
  const els = [...ELEMENTS];
  for (let i = els.length - 1; i > 0; i--) {
    const j = rnd(i + 1);
    [els[i], els[j]] = [els[j], els[i]];
  }
  return els.slice(0, 5).map((el) => statsOf(slot, el, 1 + rnd(5)));
}

/**
 * The machine's own Frogster, built to land near the player's.
 *
 * It is generated the same way and then NUDGED, not scripted: parts are rolled
 * until its total health and attack sit inside a band either side of the
 * player's, so it is neither a pushover nor a wall.  It is never built to
 * counter the player's elements -- an enemy that always resists what you
 * picked would make the six choices pointless, which is the one thing this
 * game cannot afford.
 */
function buildEnemy(player: Monster): Monster {
  const score = (m: Monster): number => m.atk * 6 + m.def * 3 + m.hp / HP_SCALE + m.spd;
  const target = score(player);
  let best: Monster | null = null;
  for (let tries = 0; tries < 40; tries++) {
    const parts = {} as Record<Slot, Part>;
    for (const slot of ORDER) parts[slot] = statsOf(slot, ELEMENTS[rnd(ELEMENTS.length)], 1 + rnd(5));
    const m = assemble(parts);
    if (!best || Math.abs(score(m) - target) < Math.abs(score(best) - target)) best = m;
    // Close enough, and a shade under the player's: the machine is meant to be
    // beatable by somebody who chose well.
    if (Math.abs(score(m) - target) < target * 0.08) return m;
  }
  return best!;
}

/**
 * Which arm the machine swings.
 *
 * It works out what each of its two arms would do and takes the better one --
 * but only four times in five.  The fifth is the other arm, which is what
 * stops a player learning the pattern in one fight and playing against a
 * lookup table for the rest of them.
 */
function enemyArm(enemy: Monster, player: Monster): 'armL' | 'armR' {
  const l = effect(enemy.parts.armL.el, player.parts.body.el) * enemy.parts.armL.atk;
  const r = effect(enemy.parts.armR.el, player.parts.body.el) * enemy.parts.armR.atk;
  const best: 'armL' | 'armR' = l >= r ? 'armL' : 'armR';
  if (Math.random() < 0.2) return best === 'armL' ? 'armR' : 'armL';
  return best;
}

// ====================================================================== art

/**
 * Where each part sits on the body, in the monster's own pixels with the feet
 * at the origin.  It is one table, and both the assembly screen and the arena
 * draw from it, so a part cannot be attached in one place and floating in the
 * other.  Nothing here overlaps anything else by more than the two pixels that
 * make a joint.
 */
const ANCHOR: Record<Slot, { x: number; y: number; w: number; h: number }> = {
  legL: { x: -7, y: -8, w: 10, h: 16 },
  legR: { x: 7, y: -8, w: 10, h: 16 },
  body: { x: 0, y: -27, w: 26, h: 22 },
  armL: { x: -17, y: -28, w: 9, h: 17 },
  armR: { x: 17, y: -28, w: 9, h: 17 },
  head: { x: 0, y: -45, w: 24, h: 19 },
};
/** How tall an assembled Frogster is, feet to crown. */
export const MONSTER_H = 54;

/** A couple of marks that say which element a part is made of. */
function detail(
  scene: Phaser.Scene,
  c: Phaser.GameObjects.Container,
  el: Element,
  x: number,
  y: number,
  w: number,
  h: number,
): void {
  const put = (dx: number, dy: number, sw: number, sh: number, col: number, ang = 0): void => {
    c.add(scene.add.rectangle(x + dx, y + dy, sw, sh, col).setAngle(ang));
  };
  const dot = (dx: number, dy: number, r: number, col: number): void => {
    c.add(scene.add.circle(x + dx, y + dy, r, col));
  };
  const q = Math.max(3, Math.min(w, h) / 3);
  switch (el) {
    case 'fire':
      put(-w / 5, -h / 4, q * 0.7, q, PALETTE.ember, 18);
      put(w / 5, -h / 3, q * 0.5, q * 0.8, PALETTE.gold, -14);
      put(0, h / 4, w * 0.5, 1, PALETTE.gold);
      break;
    case 'water':
      dot(-w / 5, -h / 5, q * 0.35, PALETTE.white);
      dot(w / 4, h / 6, q * 0.25, PALETTE.white);
      put(0, -h / 3, w * 0.55, 1, 0x9fd8ff);
      break;
    case 'grass':
      put(-w / 4, -h / 5, q * 0.9, q * 0.45, 0x9ad97a, 28);
      put(w / 4, h / 6, q * 0.8, q * 0.4, 0x9ad97a, -24);
      put(0, 0, 1, h * 0.5, 0x2f5c33);
      break;
    case 'electric':
      put(-w / 6, -h / 5, q * 0.8, 1.4, PALETTE.cream, 34);
      put(w / 8, h / 8, q * 0.7, 1.4, PALETTE.cream, -40);
      dot(w / 3, -h / 3, 1, PALETTE.white);
      break;
    case 'steel':
      put(0, -h / 4, w * 0.75, 1.4, PALETTE.bone);
      put(0, h / 5, w * 0.75, 1.4, PALETTE.bone);
      dot(-w / 3, h / 5, 1.1, PALETTE.fog);
      dot(w / 3, h / 5, 1.1, PALETTE.fog);
      break;
    default:
      put(-w / 5, h / 6, q * 0.8, q * 0.6, 0x7a5a38);
      put(w / 4, -h / 5, q * 0.6, q * 0.5, 0xc59a63, 16);
      dot(0, 0, 1.2, 0xd7c7a0);
      break;
  }
}

/**
 * One Frogster, out of whatever parts it has so far.
 *
 * Rebuilt from scratch every time a part is added, which is why a half-built
 * monster cannot end up with a leg drawn over its own head: the container is
 * emptied and filled back to front, legs first and the head last, every time.
 * `dir` is -1 for the one on the right of the arena, so both face the middle.
 */
function drawMonster(
  scene: Phaser.Scene,
  c: Phaser.GameObjects.Container,
  parts: Partial<Record<Slot, Part>>,
  dir = 1,
): void {
  c.removeAll(true);
  const piece = (slot: Slot): void => {
    const p = parts[slot];
    if (!p) return;
    const a = ANCHOR[slot];
    const x = a.x * dir;
    // A DARK EDGE ON EVERY PIECE.  Without it an arm and a torso of the same
    // element merge into one orange slab and the monster stops reading as
    // something that was ASSEMBLED, which is the whole of what it is.
    const body = scene.add.rectangle(x, a.y, a.w, a.h, EL_COLOUR[p.el]);
    body.setStrokeStyle(1, PALETTE.black, 0.55);
    c.add(body);
    c.add(scene.add.rectangle(x, a.y + a.h / 2 - 1.5, a.w - 2, 2, EL_DARK[p.el]));
    detail(scene, c, p.el, x, a.y, a.w, a.h);
  };
  // Back to front: what is behind the torso goes down first.
  piece('legL');
  piece('legR');
  piece('armL');
  piece('armR');
  piece('body');
  const h = parts.head;
  if (h) {
    piece('head');
    // AND IT IS STILL A FROG.  Two eye bumps up on top with a pupil in each,
    // and a wide mouth under them: the one thing that must survive whatever
    // six elements got bolted together.
    const a = ANCHOR.head;
    for (const s of [-1, 1]) {
      c.add(scene.add.circle(s * 7 * dir, a.y - a.h / 2 + 1, 4.5, EL_COLOUR[h.el]));
      c.add(scene.add.circle(s * 7 * dir, a.y - a.h / 2 + 1, 3, PALETTE.cream));
      c.add(scene.add.circle(s * 7 * dir + dir, a.y - a.h / 2 + 1, 1.4, PALETTE.black));
    }
    c.add(scene.add.rectangle(0, a.y + 4, 13, 2, PALETTE.black).setAlpha(0.65));
  }
}


// ==================================================================== scene

const ID = 'frogstermash' as const;
/** Seconds on the clock for one part.  Long enough to read three cards. */
const PICK_MS = 10_000;
/** Where the belt runs, and how far apart the five boxes sit on it. */
const BELT_Y = 148;
const BOX_W = 54;
const BOX_H = 32;
/** Five boxes over exactly one screen: one is always half off an edge, which
 *  is what a belt looks like.  The lit box is usable wherever it has got to. */
const BOX_GAP = 62;
const BELT_SPAN = BOX_GAP * 5;
const BELT_SPEED = 26; // px/s

type Phase = 'title' | 'pick' | 'summary' | 'intro' | 'battle' | 'over';

let scene0: Phaser.Scene | null = null;
let apiRef: MinigameApi | null = null;
let phase: Phase = 'title';
/** The one latch that stops a result being reported twice.  See `finish`. */
let ended = false;
let clock = 0;

let layer: Phaser.GameObjects.Container | null = null;
let monsterC: Phaser.GameObjects.Container | null = null;
let enemyC: Phaser.GameObjects.Container | null = null;

// ---- assembly
let stage = 0;
let offer: Part[] = [];
let picked: Partial<Record<Slot, Part>> = {};
let hi = 0;
let pickT = 0;
let beltOff = 0;
let boxes: Phaser.GameObjects.Container[] = [];
let timerBar: Phaser.GameObjects.Rectangle | null = null;
let panelText: Phaser.GameObjects.BitmapText[] = [];
let panelChip: Phaser.GameObjects.Rectangle | null = null;

// ---- battle
let player: Monster | null = null;
let enemy: Monster | null = null;
let turn: 'player' | 'enemy' = 'player';
/** True while a swing is playing.  Every attack route checks it first. */
let busy = false;
let hpBarP: Phaser.GameObjects.Rectangle | null = null;
let hpBarE: Phaser.GameObjects.Rectangle | null = null;
let hpTextP: Phaser.GameObjects.BitmapText | null = null;
let hpTextE: Phaser.GameObjects.BitmapText | null = null;
let logText: Phaser.GameObjects.BitmapText | null = null;
let armBtns: Array<{ destroy(): void }> = [];

const S = (): Phaser.Scene => scene0!;

function reset(): void {
  phase = 'title';
  ended = false;
  clock = 0;
  stage = 0;
  offer = [];
  picked = {};
  hi = 0;
  pickT = 0;
  beltOff = 0;
  boxes = [];
  timerBar = null;
  panelText = [];
  panelChip = null;
  player = null;
  enemy = null;
  turn = 'player';
  busy = false;
  hpBarP = hpBarE = null;
  hpTextP = hpTextE = null;
  logText = null;
  armBtns = [];
}

/** Everything on screen for the current phase, thrown away between phases. */
function newLayer(): Phaser.GameObjects.Container {
  layer?.destroy(true);
  for (const b of armBtns) b.destroy();
  armBtns = [];
  layer = S().add.container(0, 0);
  boxes = [];
  panelText = [];
  return layer;
}

// -------------------------------------------------------------- title card

function showTitle(): void {
  phase = 'title';
  const c = newLayer();
  c.add(S().add.rectangle(0, 18, GAME_W, 162, 0x131a2b).setOrigin(0, 0));
  const t1 = centerText(S(), GAME_W / 2, 52, 'FROGSTER', PALETTE.gold, 24);
  const t2 = centerText(S(), GAME_W / 2, 78, 'MASH', PALETTE.neon, 24);
  c.add(t1);
  c.add(t2);
  S().tweens.add({ targets: [t1, t2], scaleX: 1.06, scaleY: 1.06, duration: 420, yoyo: true, repeat: -1 });
  c.add(centerText(S(), GAME_W / 2, 104, 'BUILD IT. THEN FIGHT WITH IT.', PALETTE.tealLight));

  // A Frogster of six random parts, bouncing, so the title screen shows the
  // thing the game is about rather than the words for it.
  const demo = S().add.container(GAME_W / 2, 168);
  const parts = {} as Record<Slot, Part>;
  for (const slot of ORDER) parts[slot] = statsOf(slot, ELEMENTS[rnd(ELEMENTS.length)], 1 + rnd(5));
  drawMonster(S(), demo, parts);
  demo.setScale(0.8);
  c.add(demo);
  S().tweens.add({ targets: demo, y: 162, duration: 380, yoyo: true, repeat: -1, ease: 'Sine.easeInOut' });

  audio.sfx('stinger', 0.5);
  S().time.delayedCall(1700, () => {
    if (phase === 'title') startStage(0);
  });
}

// ---------------------------------------------------------- assembly phase

function startStage(n: number): void {
  phase = 'pick';
  stage = n;
  const slot = ORDER[n];
  offer = offerFor(slot);
  hi = 0;
  pickT = PICK_MS;
  beltOff = 0;
  const c = newLayer();

  c.add(S().add.rectangle(0, 18, GAME_W, 162, 0x10161f).setOrigin(0, 0));
  c.add(text(S(), 6, 22, `PART ${n + 1} OF 6`, PALETTE.ash));
  c.add(centerText(S(), GAME_W / 2, 26, SLOT_NAME[slot], PALETTE.gold, 16));

  // the clock, as a bar rather than a number: a bar is read without reading
  c.add(S().add.rectangle(GAME_W / 2, 36, 240, 3, PALETTE.slate));
  timerBar = S().add.rectangle(GAME_W / 2 - 120, 36, 240, 3, PALETTE.tealLight).setOrigin(0, 0.5);
  c.add(timerBar);

  // ---- what has been bolted on so far, in its own column on the left, with
  // nothing else allowed into it: the panel starts at 70 and the monster is
  // never wider than 34, so no stat line can ever cross the thing it describes.
  c.add(centerText(S(), 34, 46, 'YOURS', PALETTE.ash));
  monsterC = S().add.container(34, 126);
  monsterC.setScale(0.62);
  drawMonster(S(), monsterC, picked);
  c.add(monsterC);

  // ---- and the card for whichever box is lit, on the right
  const px = 70;
  const pw = GAME_W - px - 5;
  c.add(S().add.rectangle(px, 42, pw, 84, PALETTE.ink).setOrigin(0, 0).setStrokeStyle(1, PALETTE.steel));
  panelChip = S().add.rectangle(px + 5, 47, 9, 9, PALETTE.slate).setOrigin(0, 0);
  c.add(panelChip);
  for (let i = 0; i < 7; i++) {
    const t = text(S(), px + (i === 0 ? 18 : 5), 47 + i * 11, '', PALETTE.cream);
    panelText.push(t);
    c.add(t);
  }

  // ---- the belt, and the five boxes riding it
  c.add(S().add.rectangle(0, BELT_Y + BOX_H / 2 + 2, GAME_W, 7, PALETTE.steel).setOrigin(0, 0));
  for (let i = 0; i < 5; i++) {
    const box = S().add.container(0, BELT_Y);
    const part = offer[i];
    box.add(S().add.rectangle(0, 0, BOX_W, BOX_H, PALETTE.ink).setStrokeStyle(1, PALETTE.steel));
    box.add(S().add.rectangle(0, -BOX_H / 2 + 5, BOX_W - 4, 8, EL_DARK[part.el]));
    box.add(centerText(S(), 0, -BOX_H / 2 + 5, part.el.toUpperCase(), PALETTE.cream));
    box.add(S().add.rectangle(0, 2, 18, 12, EL_COLOUR[part.el]));
    box.add(centerText(S(), 0, BOX_H / 2 - 6, `PWR ${part.power}`, PALETTE.gold));
    box.setSize(BOX_W, BOX_H).setInteractive({ useHandCursor: true });
    box.on('pointerdown', () => {
      if (phase !== 'pick') return;
      if (hi === i) take(i);
      else highlight(i);
    });
    boxes.push(box);
    c.add(box);
  }
  c.add(centerText(S(), GAME_W / 2, 173, '[<-] [->] INSPECT   [SPACE] TAKE', PALETTE.ash));
  layoutBelt();
  highlight(0, true);
}

function layoutBelt(): void {
  boxes.forEach((b, i) => {
    b.x = (((i * BOX_GAP + beltOff) % BELT_SPAN) + BELT_SPAN) % BELT_SPAN;
  });
}

function highlight(i: number, quiet = false): void {
  hi = i;
  boxes.forEach((b, k) => {
    const frame = b.list[0] as Phaser.GameObjects.Rectangle;
    frame.setStrokeStyle(k === i ? 2 : 1, k === i ? PALETTE.gold : PALETTE.steel);
    b.setScale(k === i ? 1.06 : 1);
  });
  if (!quiet) audio.sfx('ui_hover', 0.4);
  showCard(offer[i]);
}

/** The highlighted part, spelled out: every number a choice could turn on. */
function showCard(p: Part | undefined): void {
  if (!p) {
    panelText.forEach((t) => t.setText(''));
    panelText[0]?.setText('[<-] [->] TO INSPECT A BOX');
    return;
  }
  panelChip?.setFillStyle(EL_COLOUR[p.el]);
  const lines = [
    `${p.el.toUpperCase()}  -  POWER ${p.power}  (x${POWER_MUL[p.power].toFixed(2)})`,
    `ATTACK  ${p.atk.toFixed(2)}     DEFENSE ${p.def.toFixed(2)}`,
    `SPEED   ${p.spd.toFixed(2)}     HEALTH  ${p.hp.toFixed(2)}`,
    `STRONG VS ${STRONG[p.el].join(' ').toUpperCase()}`,
    `WEAK VS   ${WEAK[p.el].join(' ').toUpperCase()}`,
    ROLE_NOTE[p.slot],
    '',
  ];
  panelText.forEach((t, i) => t.setText(lines[i] ?? '').setTint(i === 3 ? PALETTE.mossLight : i === 4 ? PALETTE.blood : PALETTE.cream));
}

/** What the slot is for, in one line, so the numbers mean something. */
const ROLE_NOTE: Record<Slot, string> = {
  legL: 'LEGS CARRY SPEED, AND A LITTLE ATTACK',
  legR: 'LEGS CARRY SPEED, AND A LITTLE ATTACK',
  armL: 'ARMS ARE ATTACK - AND THIS ARM S ELEMENT',
  armR: 'ARMS ARE ATTACK - AND THIS ARM S ELEMENT',
  body: 'ARMOR IS DEFENSE AND HEALTH, MINUS SPEED',
  head: 'THE HEAD IS DEFENSE AND HEALTH',
};

function take(i: number): void {
  if (phase !== 'pick') return;
  const part = offer[i];
  if (!part) return;
  picked[part.slot] = part;
  audio.sfx('ui_blip', 0.6);
  audio.sfx('item_thud', 0.5);
  if (monsterC) drawMonster(S(), monsterC, picked);
  if (stage + 1 < ORDER.length) {
    S().time.delayedCall(240, () => startStage(stage + 1));
    phase = 'title'; // a holding state: nothing reads the belt while it swaps
  } else {
    S().time.delayedCall(260, showSummary);
    phase = 'title';
  }
}

/** The clock ran out: take what is lit, or a box at random if nothing is. */
function autoPick(): void {
  take(hi >= 0 && hi < offer.length ? hi : rnd(offer.length));
}

// ----------------------------------------------------------- build summary

function showSummary(): void {
  phase = 'summary';
  player = assemble(picked as Record<Slot, Part>);
  enemy = buildEnemy(player);
  const c = newLayer();
  c.add(S().add.rectangle(0, 18, GAME_W, 162, 0x10161f).setOrigin(0, 0));
  c.add(centerText(S(), GAME_W / 2, 28, 'YOUR FROGSTER IS BUILT', PALETTE.gold, 16));

  monsterC = S().add.container(58, 122);
  monsterC.setScale(0.88);
  drawMonster(S(), monsterC, picked);
  c.add(monsterC);

  const px = 126;
  c.add(S().add.rectangle(px, 44, GAME_W - px - 8, 76, PALETTE.ink).setOrigin(0, 0).setStrokeStyle(1, PALETTE.steel));
  const rows: Array<[string, string, number]> = [
    ['ATTACK', player.atk.toFixed(1), PALETTE.ember],
    ['DEFENSE', player.def.toFixed(1), PALETTE.tealLight],
    ['SPEED', player.spd.toFixed(1), PALETTE.gold],
    ['HEALTH', String(player.maxHp), PALETTE.mossLight],
  ];
  rows.forEach(([k, v], i) => {
    c.add(text(S(), px + 8, 50 + i * 12, k, PALETTE.ash));
    c.add(text(S(), GAME_W - 14, 50 + i * 12, v, rows[i][2]).setOrigin(1, 0));
  });
  // ---- AND WHETHER FOUR OF THE SIX AGREED.
  if (player.synergy) {
    c.add(
      centerText(S(), GAME_W / 2, 132, `SYNERGY: ${player.synergy.toUpperCase()}  x1.1`, PALETTE.gold),
    );
    c.add(centerText(S(), GAME_W / 2, 143, 'FOUR PARTS AGREE - IT HITS AND RESISTS HARDER', PALETTE.ash));
    audio.sfx('chime', 0.5);
  } else {
    c.add(centerText(S(), GAME_W / 2, 132, 'NO SYNERGY', PALETTE.ash));
    c.add(centerText(S(), GAME_W / 2, 143, 'FOUR PARTS OF ONE ELEMENT WOULD HAVE EARNED IT', PALETTE.ash));
  }
  armBtns.push(button(S(), GAME_W / 2, 163, 'FIGHT', showIntro, { width: 74, height: 15, fill: PALETTE.blood }));
}

// ---------------------------------------------------------------- the fight

function showIntro(): void {
  if (phase !== 'summary') return;
  phase = 'intro';
  const c = newLayer();
  c.add(S().add.rectangle(0, 18, GAME_W, 162, PALETTE.black).setOrigin(0, 0));
  const t = centerText(S(), GAME_W / 2, 92, 'FIGHT!', PALETTE.gold, 32);
  c.add(t);
  S().tweens.add({ targets: t, scaleX: 1.3, scaleY: 1.3, alpha: 0.2, duration: 900 });
  audio.sfx('bell_ding', 0.7);
  audio.sfx('stinger', 0.6);
  S().time.delayedCall(950, startBattle);
}

function startBattle(): void {
  phase = 'battle';
  busy = false;
  // SPEED DECIDES WHO SWINGS FIRST, and a tie is a coin.
  turn = player!.spd > enemy!.spd ? 'player' : player!.spd < enemy!.spd ? 'enemy' : Math.random() < 0.5 ? 'player' : 'enemy';

  const c = newLayer();
  c.add(S().add.rectangle(0, 18, GAME_W, 162, 0x16202e).setOrigin(0, 0));
  c.add(S().add.rectangle(0, 122, GAME_W, 58, 0x22303f).setOrigin(0, 0));

  // ---- the two bars, and the numbers under them
  const bar = (x: number, name: string, colour: number): [Phaser.GameObjects.Rectangle, Phaser.GameObjects.BitmapText] => {
    c.add(text(S(), x, 24, name, PALETTE.ash));
    c.add(S().add.rectangle(x, 34, 130, 7, PALETTE.slate).setOrigin(0, 0));
    const fill = S().add.rectangle(x + 1, 35, 128, 5, colour).setOrigin(0, 0);
    c.add(fill);
    const num = text(S(), x + 130, 24, '', colour).setOrigin(1, 0);
    c.add(num);
    return [fill, num];
  };
  [hpBarP, hpTextP] = bar(8, 'YOURS', PALETTE.mossLight);
  [hpBarE, hpTextE] = bar(GAME_W - 138, 'CHALLENGER', PALETTE.blood);

  monsterC = S().add.container(74, 120);
  drawMonster(S(), monsterC, player!.parts);
  c.add(monsterC);
  enemyC = S().add.container(GAME_W - 74, 120);
  drawMonster(S(), enemyC, enemy!.parts, -1);
  c.add(enemyC);

  logText = centerText(S(), GAME_W / 2, 132, '', PALETTE.cream);
  c.add(logText);

  // ---- one button per arm, each wearing its own element
  (['armL', 'armR'] as const).forEach((arm, i) => {
    const p = player!.parts[arm];
    const x = i === 0 ? 84 : GAME_W - 84;
    armBtns.push(
      button(S(), x, 158, `${i === 0 ? 'L' : 'R'} ARM: ${p.el.toUpperCase()}`, () => swing(arm), {
        width: 122,
        height: 16,
        fill: EL_DARK[p.el],
        hoverFill: EL_COLOUR[p.el],
      }),
    );
    c.add(centerText(S(), x, 172, `PWR ${p.power}   ATK ${p.atk.toFixed(1)}`, PALETTE.ash));
  });

  refreshBars();
  say(turn === 'player' ? 'YOU ARE FASTER - YOU SWING FIRST' : 'IT IS FASTER - BRACE');
  if (turn === 'enemy') S().time.delayedCall(900, enemyTurn);
}

function refreshBars(): void {
  const set = (bar: Phaser.GameObjects.Rectangle | null, num: Phaser.GameObjects.BitmapText | null, m: Monster | null): void => {
    if (!bar || !num || !m) return;
    const hp = Math.max(0, m.hp);
    bar.width = Math.max(0, Math.round((hp / m.maxHp) * 128));
    num.setText(`${hp} / ${m.maxHp}`);
  };
  set(hpBarP, hpTextP, player);
  set(hpBarE, hpTextE, enemy);
}

function say(msg: string, colour: number = PALETTE.cream): void {
  logText?.setText(msg).setTint(colour);
}

/** The player's swing.  Every way in goes through here, and it is latched. */
function swing(arm: 'armL' | 'armR'): void {
  if (phase !== 'battle' || busy || turn !== 'player' || ended) return;
  busy = true;
  resolve(player!, enemy!, arm, monsterC, enemyC, 1, () => {
    if (enemy!.hp <= 0) return finishBattle(true);
    turn = 'enemy';
    S().time.delayedCall(620, enemyTurn);
  });
}

function enemyTurn(): void {
  if (phase !== 'battle' || ended) return;
  busy = true;
  const arm = enemyArm(enemy!, player!);
  resolve(enemy!, player!, arm, enemyC, monsterC, -1, () => {
    if (player!.hp <= 0) return finishBattle(false);
    turn = 'player';
    busy = false;
    say('YOUR SWING - PICK AN ARM');
  });
}

/**
 * One exchange, start to finish: the lunge, the number, the bar, the word.
 *
 * `busy` is held for the whole of it and only let go by the caller, which is
 * what stops a hammered button from queueing four swings behind one animation.
 */
function resolve(
  att: Monster,
  def: Monster,
  arm: 'armL' | 'armR',
  attC: Phaser.GameObjects.Container | null,
  defC: Phaser.GameObjects.Container | null,
  dir: number,
  done: () => void,
): void {
  const hit = damage(att, def, arm);
  const who = att === player ? 'YOU' : 'IT';
  say(`${who}: ${hit.el.toUpperCase()} STRIKE...`, EL_COLOUR[hit.el]);

  const home = attC?.x ?? 0;
  S().tweens.add({
    targets: attC,
    x: home + 22 * dir,
    duration: 150,
    yoyo: true,
    onYoyo: () => {
      def.hp = Math.max(0, def.hp - hit.dmg);
      refreshBars();
      audio.sfx(hit.band === 'strong' ? 'boom' : hit.band === 'weak' ? 'fence_thunk' : 'whack', hit.band === 'strong' ? 0.6 : 0.5);
      audio.sfx('item_thud', 0.35);
      if (defC) {
        S().tweens.add({ targets: defC, x: defC.x - 8 * dir, duration: 90, yoyo: true });
        S().cameras.main.shake(hit.band === 'strong' ? 180 : 80, hit.band === 'strong' ? 0.006 : 0.003);
      }
      const pop = centerText(S(), (defC?.x ?? 160), 84, `-${hit.dmg}`, hit.band === 'strong' ? PALETTE.gold : PALETTE.cream, 16);
      layer?.add(pop);
      S().tweens.add({ targets: pop, y: 62, alpha: 0, duration: 620, onComplete: () => pop.destroy() });
      const word =
        hit.band === 'strong' ? 'SUPER EFFECTIVE!' : hit.band === 'weak' ? 'NOT VERY EFFECTIVE' : 'A CLEAN HIT';
      say(`${who}: ${hit.el.toUpperCase()} - ${word}${hit.synergy ? ' +SYNERGY' : ''}`,
        hit.band === 'strong' ? PALETTE.gold : hit.band === 'weak' ? PALETTE.ash : PALETTE.cream);
    },
    onComplete: () => {
      if (attC) attC.x = home;
      S().time.delayedCall(360, done);
    },
  });
}

// --------------------------------------------------------------- the result

function finishBattle(won: boolean): void {
  phase = 'over';
  busy = true;
  for (const b of armBtns) b.destroy();
  armBtns = [];

  // BOTH OF THEM STEP OUT TO THE EDGES, so the card that lands between them
  // does not sit on top of the two things the whole game was about.
  const loser = won ? enemyC : monsterC;
  if (loser) S().tweens.add({ targets: loser, x: won ? 292 : 28, angle: 80, alpha: 0.4, y: 132, duration: 520 });
  const winner = won ? monsterC : enemyC;
  if (winner) {
    S().tweens.add({ targets: winner, x: won ? 28 : 292, duration: 420 });
    S().tweens.add({ targets: winner, y: (winner.y ?? 120) - 8, duration: 260, yoyo: true, repeat: 3 });
  }

  audio.sfx(won ? 'zone_clear' : 'death_stinger', 0.7);
  S().time.delayedCall(700, () => {
    const panel = S().add.rectangle(GAME_W / 2, 96, 212, 76, PALETTE.ink).setDepth(60).setStrokeStyle(1, won ? PALETTE.gold : PALETTE.steel);
    layer?.add(panel);
    const head = centerText(S(), GAME_W / 2, 76, won ? 'FROGSTER CHAMPION!' : 'FROGSTER DEFEATED!', won ? PALETTE.gold : PALETTE.fog, 16).setDepth(61);
    layer?.add(head);
    S().tweens.add({ targets: head, scaleX: 1.08, scaleY: 1.08, duration: 300, yoyo: true, repeat: won ? 3 : 0 });

    if (won) {
      // The reward ANIMATION.  The tokens themselves are the shell's business
      // and arrive when `finish` calls `api.win`, once.
      const gain = centerText(S(), GAME_W / 2, 100, '+30 TOKENS', PALETTE.gold, 16).setDepth(61);
      layer?.add(gain);
      S().tweens.add({ targets: gain, y: 94, duration: 420, yoyo: true, repeat: -1 });
      audio.sfx('cha_ching', 0.6);
      layer?.add(centerText(S(), GAME_W / 2, 118, `BALANCE AFTER: ${apiRef!.balance() + 30}`, PALETTE.ash).setDepth(61));
    } else {
      layer?.add(centerText(S(), GAME_W / 2, 100, 'NO REWARD. NO REFUND.', PALETTE.ash).setDepth(61));
      layer?.add(centerText(S(), GAME_W / 2, 118, `BALANCE: ${apiRef!.balance()}`, PALETTE.ash).setDepth(61));
    }
    armBtns.push(
      button(S(), GAME_W / 2, 148, 'BACK TO THE ARCADE', () => finish(won), {
        width: 150,
        height: 16,
        fill: won ? PALETTE.tealDark : PALETTE.slate,
      }),
    );
  });
}

/**
 * Say which way it went, once and once only.
 *
 * `ended` latches before anything else happens, so a double-tapped button, a
 * tween that fires twice and a player who finds a second route all end up
 * reporting the same single result -- and the shell's own latch is behind
 * this one, which is two locks on the only door the thirty tokens come out of.
 */
function finish(won: boolean): void {
  if (ended) return;
  ended = true;
  for (const b of armBtns) b.destroy();
  armBtns = [];
  if (won) apiRef!.win();
  else apiRef!.lose();
}

// =================================================================== module

export const frogsterMash: MinigameModule = {
  id: ID,
  title: 'FROGSTER MASH',
  music: 'game_frogstermash',
  rules: 'build a frogster out of six parts, then fight with it',
  tutorial: {
    objective: [
      'PICK SIX PARTS OFF THE BELT: LEGS, ARMS, ARMOR, HEAD.',
      'EACH PART HAS AN ELEMENT. ELEMENTS BEAT ELEMENTS.',
      'THEN FIGHT. EMPTY THE CHALLENGER AND TAKE THE 30.',
    ],
    controls: [
      ['LEFT/RIGHT', 'INSPECT THE BOXES'],
      ['SPACE', 'TAKE THE LIT BOX'],
      ['CLICK', 'INSPECT, THEN CLICK AGAIN TO TAKE'],
      ['1 / 2', 'SWING LEFT OR RIGHT ARM'],
    ],
  },
  touch: {
    stick: 'lr',
    arrows: true,
    buttons: [
      { label: 'TAKE', key: 'SPACE', primary: true },
      { label: 'L', key: 'ONE' },
      { label: 'R', key: 'TWO' },
    ],
  },

  create(scene: Phaser.Scene, api: MinigameApi) {
    scene0 = scene;
    apiRef = api;
    layer = null;
    reset();

    const kb = scene.input.keyboard;
    kb?.on('keydown-LEFT', () => {
      if (phase === 'pick') highlight((hi + offer.length - 1) % offer.length);
    });
    kb?.on('keydown-RIGHT', () => {
      if (phase === 'pick') highlight((hi + 1) % offer.length);
    });
    kb?.on('keydown-A', () => {
      if (phase === 'pick') highlight((hi + offer.length - 1) % offer.length);
    });
    kb?.on('keydown-D', () => {
      if (phase === 'pick') highlight((hi + 1) % offer.length);
    });
    kb?.on('keydown-SPACE', () => {
      if (phase === 'pick') take(hi);
    });
    kb?.on('keydown-ENTER', () => {
      if (phase === 'pick') take(hi);
    });
    kb?.on('keydown-ONE', () => {
      if (phase === 'battle') swing('armL');
    });
    kb?.on('keydown-TWO', () => {
      if (phase === 'battle') swing('armR');
    });

    showTitle();

    if (import.meta.env?.DEV) {
      (window as unknown as Record<string, unknown>).__mash = {
        state: () => ({
          phase,
          stage,
          slot: ORDER[stage],
          hi,
          pickT: Math.round(pickT),
          ended,
          turn,
          busy,
          offer: offer.map((p) => ({ el: p.el, power: p.power, atk: +p.atk.toFixed(3), def: +p.def.toFixed(3), spd: +p.spd.toFixed(3), hp: +p.hp.toFixed(3) })),
          picked: ORDER.filter((s) => picked[s]).map((s) => ({ slot: s, el: picked[s]!.el, power: picked[s]!.power })),
          player: player && { atk: +player.atk.toFixed(3), def: +player.def.toFixed(3), spd: +player.spd.toFixed(3), hp: player.hp, maxHp: player.maxHp, synergy: player.synergy },
          enemy: enemy && { atk: +enemy.atk.toFixed(3), def: +enemy.def.toFixed(3), spd: +enemy.spd.toFixed(3), hp: enemy.hp, maxHp: enemy.maxHp, synergy: enemy.synergy },
          log: logText?.text ?? '',
        }),
        /** Where the five boxes are, so a harness can see the belt moving. */
        belt: () => boxes.map((b) => Math.round(b.x)),
        highlight: (i: number) => highlight(i),
        take: (i: number) => take(i),
        /** Take a box of a named element at this stage, if one is on offer. */
        takeEl: (el: Element) => {
          const i = offer.findIndex((p) => p.el === el);
          if (i >= 0) take(i);
          return i >= 0;
        },
        swing: (arm: 'armL' | 'armR') => swing(arm),
        /** Put a monster on the ropes, to reach the end of a fight quickly. */
        setHp: (who: 'player' | 'enemy', n: number) => {
          const m = who === 'player' ? player : enemy;
          if (m) m.hp = n;
          refreshBars();
        },
        /** The rules, exposed so the arithmetic can be checked rather than watched. */
        rules: { BASE, STRONG, WEAK, POWER_MUL, effect, statsOf, assemble, damage },
      };
      scene.events.once(Phaser.Scenes.Events.SHUTDOWN, () => {
        delete (window as unknown as Record<string, unknown>).__mash;
      });
    }
  },

  update(_time: number, delta: number) {
    clock += delta;
    if (phase !== 'pick') return;
    // The belt runs whether or not anybody is looking at it.
    beltOff -= (BELT_SPEED * delta) / 1000;
    layoutBelt();
    const before = pickT;
    pickT -= delta;
    if (timerBar) timerBar.width = Math.max(0, (pickT / PICK_MS) * 240);
    // One clank per box-width of travel, which is a belt and not a drone.
    if (Math.floor(-beltOff / 14) !== Math.floor((-beltOff + (BELT_SPEED * delta) / 1000) / 14)) {
      audio.sfx('wheel_tick', 0.12);
    }
    if (before > 2000 && pickT <= 2000) audio.sfx('buzzer', 0.25);
    if (pickT <= 0) autoPick();
  },

  destroy() {
    const kb = scene0?.input.keyboard;
    for (const k of ['LEFT', 'RIGHT', 'A', 'D', 'SPACE', 'ENTER', 'ONE', 'TWO']) kb?.off(`keydown-${k}`);
    for (const b of armBtns) b.destroy();
    armBtns = [];
    layer?.destroy(true);
    layer = null;
    monsterC = null;
    enemyC = null;
    scene0 = null;
    apiRef = null;
    reset();
  },
};
